In [1]:
import yfinance as yf

msft = yf.Ticker("MSFT") #on fetch les données de Microsoft

# get all stock info
msft.info

{'address1': 'One Microsoft Way',
 'city': 'Redmond',
 'state': 'WA',
 'zip': '98052-6399',
 'country': 'United States',
 'phone': '425 882 8080',
 'website': 'https://www.microsoft.com',
 'industry': 'Software - Infrastructure',
 'industryKey': 'software-infrastructure',
 'industryDisp': 'Software - Infrastructure',
 'sector': 'Technology',
 'sectorKey': 'technology',
 'sectorDisp': 'Technology',
 'longBusinessSummary': 'Microsoft Corporation develops and supports software, services, devices and solutions worldwide. The Productivity and Business Processes segment offers office, exchange, SharePoint, Microsoft Teams, office 365 Security and Compliance, Microsoft viva, and Microsoft 365 copilot; and office consumer services, such as Microsoft 365 consumer subscriptions, Office licensed on-premises, and other office services. This segment also provides LinkedIn; and dynamics business solutions, including Dynamics 365, a set of intelligent, cloud-based applications across ERP, CRM, power apps, and power automate; and on-premises ERP and CRM applications. The Intelligent Cloud segment offers server products and cloud services, such as azure and other cloud services; SQL and windows server, visual studio, system center, and related client access licenses, as well as nuance and GitHub; and enterprise services including enterprise support services, industry solutions, and nuance professional services. The More Personal Computing segment offers Windows, including windows OEM licensing and other non-volume licensing of the Windows operating system; Windows commercial comprising volume licensing of the Windows operating system, windows cloud services, and other Windows commercial offerings; patent licensing; and windows Internet of Things; and devices, such as surface, HoloLens, and PC accessories. Additionally, this segment provides gaming, which includes Xbox hardware and content, and first- and third-party content; Xbox game pass and other subscriptions, cloud gaming, advertising, third-party disc royalties, and other cloud services; and search and news advertising, which includes Bing, Microsoft News and Edge, and third-party affiliates. The company sells its products through OEMs, distributors, and resellers; and directly through digital marketplaces, online, and retail stores. The company was founded in 1975 and is headquartered in Redmond, Washington.',
 'fullTimeEmployees': 221000,
 'companyOfficers': [{'maxAge': 1,
   'name': 'Mr. Satya  Nadella',
   'age': 56,
   'title': 'Chairman & CEO',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'totalPay': 9276400,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Bradford L. Smith LCA',
   'age': 64,
   'title': 'President & Vice Chairman',
   'yearBorn': 1959,
   'fiscalYear': 2023,
   'totalPay': 3591277,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Amy E. Hood',
   'age': 51,
   'title': 'Executive VP & CFO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 3452196,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Judson B. Althoff',
   'age': 50,
   'title': 'Executive VP & Chief Commercial Officer',
   'yearBorn': 1973,
   'fiscalYear': 2023,
   'totalPay': 3355797,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Christopher David Young',
   'age': 51,
   'title': 'Executive Vice President of Business Development, Strategy & Ventures',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'totalPay': 2460507,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Ms. Alice L. Jolla',
   'age': 56,
   'title': 'Corporate VP & Chief Accounting Officer',
   'yearBorn': 1967,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. James Kevin Scott',
   'age': 51,
   'title': 'Executive VP of AI & CTO',
   'yearBorn': 1972,
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Brett  Iversen',
   'title': 'Vice President of Investor Relations',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Hossein  Nowbar',
   'title': 'Chief Legal Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0},
  {'maxAge': 1,
   'name': 'Mr. Frank X. Shaw',
   'title': 'Chief Communications Officer',
   'fiscalYear': 2023,
   'exercisedValue': 0,
   'unexercisedValue': 0}],
 'auditRisk': 2,
 'boardRisk': 5,
 'compensationRisk': 2,
 'shareHolderRightsRisk': 2,
 'overallRisk': 1,
 'governanceEpochDate': 1706745600,
 'compensationAsOfEpochDate': 1703980800,
 'maxAge': 86400,
 'priceHint': 2,
 'previousClose': 402.18,
 'open': 410.19,
 'dayLow': 408.57,
 'dayHigh': 412.8,
 'regularMarketPreviousClose': 402.18,
 'regularMarketOpen': 410.19,
 'regularMarketDayLow': 408.57,
 'regularMarketDayHigh': 412.8,
 'dividendRate': 3.0,
 'dividendYield': 0.0075,
 'exDividendDate': 1707868800,
 'payoutRatio': 0.2523,
 'fiveYearAvgDividendYield': 0.98,
 'beta': 0.899,
 'trailingPE': 37.21609,
 'forwardPE': 33.328743,
 'volume': 17567649,
 'regularMarketVolume': 17567649,
 'averageVolume': 24788800,
 'averageVolume10days': 22196100,
 'averageDailyVolume10Day': 22196100,
 'bid': 411.6,
 'ask': 411.62,
 'bidSize': 1000,
 'askSize': 1000,
 'marketCap': 3058443223040,
 'fiftyTwoWeekLow': 245.61,
 'fiftyTwoWeekHigh': 420.82,
 'priceToSalesTrailing12Months': 13.438804,
 'fiftyDayAverage': 389.912,
 'twoHundredDayAverage': 349.339,
 'trailingAnnualDividendRate': 2.86,
 'trailingAnnualDividendYield': 0.0071112434,
 'currency': 'USD',
 'enterpriseValue': 3018748854272,
 'profitMargins': 0.36269,
 'floatShares': 7418993357,
 'sharesOutstanding': 7430439936,
 'sharesShort': 49875453,
 'sharesShortPriorMonth': 51394982,
 'sharesShortPreviousMonthDate': 1703808000,
 'dateShortInterest': 1706659200,
 'sharesPercentSharesOut': 0.0067000003,
 'heldPercentInsiders': 0.00056,
 'heldPercentInstitutions': 0.73838997,
 'shortRatio': 1.98,
 'shortPercentOfFloat': 0.0067000003,
 'impliedSharesOutstanding': 7430439936,
 'bookValue': 32.06,
 'priceToBook': 12.838738,
 'lastFiscalYearEnd': 1688083200,
 'nextFiscalYearEnd': 1719705600,
 'mostRecentQuarter': 1703980800,
 'earningsQuarterlyGrowth': 0.332,
 'netIncomeToCommon': 82541002752,
 'trailingEps': 11.06,
 'forwardEps': 12.35,
 'pegRatio': 2.48,
 'lastSplitFactor': '2:1',
 'lastSplitDate': 1045526400,
 'enterpriseToRevenue': 13.264,
 'enterpriseToEbitda': 25.49,
 '52WeekChange': 0.5786003,
 'SandP52WeekChange': 0.24162579,
 'lastDividendValue': 0.75,
 'lastDividendDate': 1707868800,
 'exchange': 'NMS',
 'quoteType': 'EQUITY',
 'symbol': 'MSFT',
 'underlyingSymbol': 'MSFT',
 'shortName': 'Microsoft Corporation',
 'longName': 'Microsoft Corporation',
 'firstTradeDateEpochUtc': 511108200,
 'timeZoneFullName': 'America/New_York',
 'timeZoneShortName': 'EST',
 'uuid': 'b004b3ec-de24-385e-b2c1-923f10d3fb62',
 'messageBoardId': 'finmb_21835',
 'gmtOffSetMilliseconds': -18000000,
 'currentPrice': 411.61,
 'targetHighPrice': 546.44,
 'targetLowPrice': 298.1,
 'targetMeanPrice': 455.86,
 'targetMedianPrice': 455.0,
 'recommendationMean': 1.7,
 'recommendationKey': 'buy',
 'numberOfAnalystOpinions': 44,
 'totalCash': 80981999616,
 'totalCashPerShare': 10.899,
 'ebitda': 118427000832,
 'totalDebt': 111358001152,
 'quickRatio': 1.096,
 'currentRatio': 1.218,
 'totalRevenue': 227583000576,
 'debtToEquity': 46.736,
 'revenuePerShare': 30.612,
 'returnOnAssets': 0.1519,
 'returnOnEquity': 0.39174,
 'freeCashflow': 58680999936,
 'operatingCashflow': 102646996992,
 'earningsGrowth': 0.332,
 'revenueGrowth': 0.176,
 'grossMargins': 0.69815004,
 'ebitdaMargins': 0.52037,
 'operatingMargins': 0.43585998,
 'financialCurrency': 'USD',
 'trailingPegRatio': 2.3694}

In [2]:
# get historical market data
hist = msft.history(period="1mo")
hist.tail()

/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/venv/lib/python3.10/site-packages/yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
2024-02-15 00:00:00-05:00,408.140015,409.130005,404.290009,406.559998,21825500,0.0,0.0
2024-02-16 00:00:00-05:00,407.959991,408.290009,403.440002,404.059998,22281100,0.0,0.0
2024-02-20 00:00:00-05:00,403.239990,404.489990,398.010010,402.790009,24307900,0.0,0.0
2024-02-21 00:00:00-05:00,400.170013,402.290009,397.220001,402.179993,18631100,0.0,0.0
2024-02-22 00:00:00-05:00,410.190002,412.799988,408.570007,411.619995,17566998,0.0,0.0

In [3]:
# show actions (dividends, splits, capital gains)
msft.actions

                           Dividends  Stock Splits
Date
2024-02-14 00:00:00-05:00       0.75           0.0

In [4]:
# show share count
msft.get_shares_full(start="2022-01-01", end=None)

2022-01-27 00:00:00-05:00    7496869888
2022-02-04 00:00:00-05:00    7800719872
2022-02-05 00:00:00-05:00    7496869888
2022-02-11 00:00:00-05:00    7496869888
2022-03-04 00:00:00-05:00    7605040128
                                ...
2024-02-07 00:00:00-05:00    7430439936
2024-02-07 00:00:00-05:00    7432640000
2024-02-14 00:00:00-05:00    7430439936
2024-02-15 00:00:00-05:00    7430439936
2024-02-17 00:00:00-05:00    7430439936
Length: 129, dtype: int64

In [5]:
# Show future and historic earnings dates, returns at most next 4 quarters and last 8 quarters by default. 
# Note: If more are needed use msft.get_earnings_dates(limit=XX) with increased limit argument.
msft.earnings_dates

                           EPS Estimate  Reported EPS  Surprise(%)
Earnings Date
2025-01-28 16:00:00-05:00           NaN           NaN          NaN
2024-10-22 06:00:00-04:00           NaN           NaN          NaN
2024-07-23 06:00:00-04:00           NaN           NaN          NaN
2024-04-23 06:00:00-04:00          2.61           NaN          NaN
2024-01-30 16:00:00-05:00          2.78          2.93       0.0534
2023-10-24 16:00:00-04:00          2.65          2.99       0.1270
2023-07-25 16:00:00-04:00          2.55          2.69       0.0549
2023-04-25 16:00:00-04:00          2.23          2.45       0.0981
2023-01-24 16:00:00-05:00          2.29          2.32       0.0109
2022-10-25 16:00:00-04:00          2.30          2.35       0.0205
2022-07-26 16:00:00-04:00          2.29          2.23      -0.0274
2022-04-26 16:00:00-04:00          2.19          2.22       0.0160

In [6]:
from pandas_datareader import data as pdr

import yfinance as yf
yf.pdr_override() # <== that's all it takes :-)

# download dataframe
data = pdr.get_data_yahoo("SPY", start="2017-01-01", end="2017-04-30")

/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/venv/lib/python3.10/site-packages/yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

In [7]:
import yfinance as yf
data = yf.download("SPY AAPL", period="1mo") #permets de télécharger plusieurs actions en même temps et les afficher dans un tableau
data

#pour accéder seulement à la colonne close

data['Close']

/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/venv/lib/python3.10/site-packages/yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/venv/lib/python3.10/site-packages/yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  2 of 2 completed

Ticker            AAPL         SPY
Date
2024-01-22  193.889999  483.450012
2024-01-23  195.179993  484.859985
2024-01-24  194.500000  485.390015
2024-01-25  194.169998  488.029999
2024-01-26  192.419998  487.410004
2024-01-29  191.729996  491.269989
2024-01-30  188.039993  490.890015
2024-01-31  184.399994  482.880005
2024-02-01  186.860001  489.200012
2024-02-02  185.850006  494.350006
2024-02-05  187.679993  492.549988
2024-02-06  189.300003  493.980011
2024-02-07  189.410004  498.100006
2024-02-08  188.320007  498.320007
2024-02-09  188.850006  501.200012
2024-02-12  187.149994  500.980011
2024-02-13  185.039993  494.079987
2024-02-14  184.149994  498.570007
2024-02-15  183.860001  502.010010
2024-02-16  182.309998  499.510010
2024-02-20  181.559998  496.760010
2024-02-21  182.320007  497.209991
2024-02-22  184.410004  507.809998

In [8]:
#puis à close de SPY

data['Close']['SPY']

Date
2024-01-22    483.450012
2024-01-23    484.859985
2024-01-24    485.390015
2024-01-25    488.029999
2024-01-26    487.410004
2024-01-29    491.269989
2024-01-30    490.890015
2024-01-31    482.880005
2024-02-01    489.200012
2024-02-02    494.350006
2024-02-05    492.549988
2024-02-06    493.980011
2024-02-07    498.100006
2024-02-08    498.320007
2024-02-09    501.200012
2024-02-12    500.980011
2024-02-13    494.079987
2024-02-14    498.570007
2024-02-15    502.010010
2024-02-16    499.510010
2024-02-20    496.760010
2024-02-21    497.209991
2024-02-22    507.809998
Name: SPY, dtype: float64

In [11]:
#conversion de ce dataframe en csv
data.to_csv('/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/data/data.csv')

In [23]:
#faisons une classe qui load les données avec poour attributs le nom du stock à récupérer, la période. Comme méthode, on aura une méthode qui permet de récupérer les données et une autre qui permet de les sauvegarder en csv
import pandas as pd

class data:
    def __init__(self, stock, period):
        self.stock = stock
        self.period = period
        self.data = yf.download(stock, period=period)
    def save(self, path):
        self.data.to_csv(path)
    def load_from_csv(self, path):
        self.data = pd.read_csv(path)
        return self.data
    def show(self):
        return self.data

In [24]:
#exemple afficher une instance de classe 

nikkei = data('^N225', '1mo')
nikkei.show()

/home/lucien/Bureau/préparation_stage/quant_project/straddle_backtesting/venv/lib/python3.10/site-packages/yfinance/utils.py:775: FutureWarning: The 'unit' keyword in TimedeltaIndex construction is deprecated and will be removed in a future version. Use pd.to_timedelta instead.
  df.index += _pd.TimedeltaIndex(dst_error_hours, 'h')
[*********************100%%**********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2024-01-22,36294.101562,36571.800781,36225.910156,36546.949219,36546.949219,100000000
2024-01-23,36605.300781,36984.511719,36436.070312,36517.570312,36517.570312,111500000
2024-01-24,36415.660156,36471.390625,36104.890625,36226.480469,36226.480469,108600000
2024-01-25,36213.140625,36312.359375,35912.539062,36236.468750,36236.468750,94600000
2024-01-26,36003.000000,36060.398438,35687.578125,35751.070312,35751.070312,109600000
2024-01-29,35814.289062,36186.871094,35813.769531,36026.941406,36026.941406,95500000
2024-01-30,36196.640625,36249.031250,36039.308594,36065.859375,36065.859375,87900000
2024-01-31,35747.890625,36292.531250,35704.578125,36286.710938,36286.710938,111100000
2024-02-01,36008.558594,36146.359375,35924.601562,36011.460938,36011.460938,118100000
2024-02-02,36249.988281,36441.089844,36083.609375,36158.019531,36158.019531,114800000
2024-02-05,36419.339844,36452.621094,36213.000000,36354.160156,36354.160156,130500000
2024-02-06,36249.078125,36294.480469,36065.980469,36160.660156,36160.660156,134700000
2024-02-07,36002.988281,36195.500000,35854.628906,36119.921875,36119.921875,126500000
2024-02-08,36258.839844,36956.968750,36206.199219,36863.281250,36863.281250,151000000
2024-02-09,36915.441406,37287.261719,36807.031250,36897.421875,36897.421875,146800000
2024-02-13,37248.359375,38010.691406,37184.101562,37963.968750,37963.968750,140500000
2024-02-14,37712.871094,37825.851562,37594.468750,37703.320312,37703.320312,120300000
2024-02-15,38017.828125,38188.738281,37935.359375,38157.941406,38157.941406,130000000
2024-02-16,38517.371094,38865.058594,38361.550781,38487.238281,38487.238281,151700000
2024-02-19,38473.410156,38555.839844,38281.699219,38470.378906,38470.378906,102000000
2024-02-20,38510.371094,38742.328125,38288.039062,38363.609375,38363.609375,108500000
2024-02-21,38191.968750,38339.699219,38095.148438,38262.160156,38262.160156,104700000
2024-02-22,38517.371094,39156.968750,38508.070312,39098.679688,39098.679688,0